name: .NET Core

on:
  push:
    branches: 
      - master
      - Develop

  pull_request:
    branches:
      - master
      - Develop

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./Smart_Currency_Converter.UnitTests

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Current Directory:
      run: echo "The current working directory: $PWD"

    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore

    - name: Build
      run: dotnet ./build Smart_Currency_Converter.UnitTests --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ./Smart_Currency_Converter.UnitTests --no-restore --verbosity normal
